# Generated by Django 6.0.1 on 2026-01-31 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='cretaed_at',
            new_name='created_at',
        ),
    ]
